const exp=require("express")
const cors=require('cors')
const dbconnect = require("./APP/DB/Databaseconnect")
const userroute = require("./APP/Routers/web/LoginRegister")
const categoryroute = require("./APP/Routers/admin/CategoryRouter")
const subcategoryroute = require("./APP/Routers/admin/SubcategoryRouter")
const Tableroute = require("./APP/Routers/admin/TableRoute")
const cartdataroute = require("./APP/Routers/web/Cartoperation")
const Reportroute = require("./APP/Routers/admin/Reportroute")

const app=exp()
app.use(cors())
app.use(exp.json())
require('dotenv').config()
app.use(userroute)
app.use(categoryroute)
app.use(subcategoryroute)
app.use(Tableroute)
app.use(cartdataroute)
app.use(Reportroute)
dbconnect()
app.listen(process.env.PORT,()=>{
   console.log(`the app is running on port ${process.env.PORT}`)
})